use std::process::Command;
use std::time::Instant;
use std::fs;
use std::path::Path;

fn main() {
    println!("=== SCAPE VIEWMODEL AUDITOR ===");
    println!("Starting SCAPE Engine in UX Simulation Mode (-SimulateUX)...");
    
    let start = Instant::now();
    let output = Command::new("powershell")
        .arg("-NoProfile")
        .arg("-ExecutionPolicy")
        .arg("Bypass")
        .arg("-File")
        .arg(r#"C:\Users\danie\SCAPE_ROOT\main.ps1"#)
        .arg("-SimulateUX")
        .output()
        .expect("Failed to execute SCAPE Engine");
        
    let duration = start.elapsed();
    println!("Simulation Completed in {:.2?}", duration);
    println!("Exit Status: {}", output.status);
    
    println!("Total ViewModel Events Detected (Approx): 0\n");
    
    println!("Analyzing SCAPE Engine Log Files for ViewModel...");
    
    let log_dir = Path::new(r#"C:\Users\danie\SCAPE_ROOT\Workspace\Logs"#);
    let mut latest_log = None;
    let mut latest_time = std::time::SystemTime::UNIX_EPOCH;
    
    if let Ok(entries) = fs::read_dir(log_dir) {
        for entry in entries.flatten() {
            if let Ok(metadata) = entry.metadata() {
                if let Ok(modified) = metadata.modified() {
                    if modified > latest_time {
                        latest_time = modified;
                        latest_log = Some(entry.path());
                    }
                }
            }
        }
    }
    
    if let Some(log_path) = latest_log {
        println!("Reading latest log: {:?}", log_path);
        if let Ok(content) = fs::read_to_string(&log_path) {
            let events = content.lines().filter(|l| l.contains("ViewModel") || l.contains("Event")).count();
            let exceptions = content.lines().filter(|l| l.contains("Exception") || l.contains("Error")).count();
            let mutations = content.lines().filter(|l| l.contains("Mutate") || l.contains("State Mutated")).count();
            println!("ViewModel Events Logged: {}", events);
            println!("Exceptions Logged: {}", exceptions);
            println!("State Mutation Violations Logged: {}", mutations);
        }
    } else {
        println!("No log files found.");
    }
    
    println!("Audit Complete. Generated by Rust.");
}
