use std::process::{Command, Stdio};
use std::time::Instant;
use std::io::{Read, BufRead, BufReader};
use std::fs;
use std::path::Path;

fn main() {
    println!("=== SCAPE MODEL AUDITOR ===");
    println!("Starting SCAPE Engine in UX Simulation Mode (-SimulateUX)...");

    let script_path = r#"C:\Users\danie\SCAPE_ROOT\main.ps1"#;
    
    let start_time = Instant::now();

    // Spawn PowerShell
    let mut child = Command::new("powershell.exe")
        .arg("-NoProfile")
        .arg("-ExecutionPolicy")
        .arg("Bypass")
        .arg("-File")
        .arg(script_path)
        .arg("-SimulateUX")
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("Failed to start PowerShell process");

    let stdout = child.stdout.take().expect("Failed to open stdout");
    let stderr = child.stderr.take().expect("Failed to open stderr");

    let mut stdout_reader = BufReader::new(stdout);
    
    let mut logs = Vec::new();
    let mut line = String::new();
    let mut model_events = 0;
    
    while stdout_reader.read_line(&mut line).unwrap() > 0 {
        if line.trim().is_empty() { continue; }
        logs.push(line.clone());
        if line.contains("Write-Host") || line.contains("Write-Output") || line.contains("Blocking IO") {
            model_events += 1;
        }
        line.clear();
    }

    let status = child.wait().expect("Failed to wait on child");
    let elapsed = start_time.elapsed();

    println!("Simulation Completed in {:.2?}", elapsed);
    println!("Exit Status: {}", status);
    println!("Total Model/Domain Purity Violations (Approx): {}", model_events);

    // Inspect the Workspace/Logs folder to analyze the actual engine metrics
    let log_dir = Path::new(r#"C:\Users\danie\SCAPE_ROOT\Workspace\Logs"#);
    if log_dir.exists() {
        println!("\nAnalyzing SCAPE Engine Log Files for Model Purity...");
        if let Ok(entries) = fs::read_dir(log_dir) {
            let mut latest_log = None;
            let mut latest_time = std::time::SystemTime::UNIX_EPOCH;

            for entry in entries.flatten() {
                if let Ok(meta) = entry.metadata() {
                    if let Ok(modified) = meta.modified() {
                        if modified > latest_time {
                            latest_time = modified;
                            latest_log = Some(entry.path());
                        }
                    }
                }
            }

            if let Some(log_path) = latest_log {
                println!("Reading latest log: {:?}", log_path);
                if let Ok(content) = fs::read_to_string(&log_path) {
                    let mut io_blocks = 0;
                    let mut exceptions = 0;
                    let mut oop_state = 0;
                    for log_line in content.lines() {
                        if log_line.contains("Blocking") {
                            io_blocks += 1;
                        }
                        if log_line.contains("Exception") || log_line.contains("Error") {
                            exceptions += 1;
                        }
                        if log_line.contains("Mutable State") {
                            oop_state += 1;
                        }
                    }
                    println!("IO Blocking Events Logged: {}", io_blocks);
                    println!("Exceptions Logged: {}", exceptions);
                    println!("Mutable State Violations Logged: {}", oop_state);
                }
            }
        }
    }

    println!("Audit Complete. Generated by Rust.");
}
